---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: my-app
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: my-app@sha256:46b863d168109cf127b191a1182280647d3ae369d2d62c0dcee6b99d40d21acf
        namespace: georgechiu-dev
      name: latest
